### ISSUE TITLE
Getting error while saving the saving the template

### ISSUE THREAD

**Issue by pvadadoriya01** [manuongithub/meditor#13]
Here's the error:

`Uncaught TypeError: window.opener is null` from initSaveAction.js Line: 47.

![image](https://user-images.githubusercontent.com/87417569/127448042-b34b9571-6395-4d56-8130-c7a208aad650.png)

Please help me with this issue.

Anyway great plugin sir, appreciate your work 👍

**Comment by manuongithub** [comment]
saving is not supported
