### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by DevRaviWorks** [manuongithub/meditor#5]
**Describe the bug**
Can you please help me to load dynamic content from database .
As this plugin uses static template. So after saving the template into the DB I am not able to edit it again. 
This Might be because of missing selectors in the table structure received on save the content.
Please instruct me to  work with dynamic content.

**Version**
"2.0.0"

**To Reproduce**
Using with a CMS need to load dynamic content straight form the DB

**Expected behavior**
It should also work with the dynamic data

**Screenshots**
Please let me know what is suitable for loading data dynamic? Screenshot attached 
![image](https://user-images.githubusercontent.com/68181691/103870852-44b5b980-50f2-11eb-8059-a1a0f21362b7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : all

**Comment by manuongithub** [comment]
This is not a bug.. it rather is an enhancement...
